apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
    spec:
      containers:
      - name: java-maven-app
        image: harishyam/java-maven-app:latest
        ports:
        - containerPort: 8080

